### PR TITLE
Week 2 Warm Up Exercises

### PR DESCRIPTION
**Pull request by paisely65**
I think that this is the correct pull request. I can see the commit messages I made. I tried to do the pull request before but forgot to do git push. 

Hope this assignment is successful.

### CODE REVIEW

**Comment by paisely65** [comment]
Not sure if I should close the pull request.  I did not see that ant tests were passed but did not see any failed either.

**Comment by paisely65** [comment]
I'm not sure about  the "Fixes bad runtests direction." This was part of the first pull request that I submitted.

**Comment by paisely65** [comment]
Should my username be in the pull request link?

**Comment by paisely65** [comment]
I made the change to task_06 and modified the pull request

**Comment by cheuschober** [comment]
Retest this please.

**Pull request merged**
